### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by lixd** [bojand/ghz#268]
**Proto file(s)**
```protobuf
syntax = "proto3";
option go_package = "github.com/lixd/grpc-go-example/helloworld/helloworld";
package helloworld;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}

```

**Command line arguments / config**
```sh
ghz -c 10 -n 2000    --insecure    --proto ./hello_world.proto    --call helloworld.Greeter.SayHello    -d '{"name":"Joe"}'    --rps 200 --concurrency-schedule=step --concurrency-start=5 --concurrency-step=5 --concurrency-end=50 --concurrency-step-duration=5s    -o report.json -O pretty    0.0.0.0:50051
```

**Describe the bug**
panic: send on closed channel

goroutine 34 [running]:
github.com/bojand/ghz/load.(*StepWorkerTicker).Run.func1(0xc0003784b0, 0xc000317710, 0xc016b4cd6897dd94, 0x3ae559, 0x12cda60, 0x1, 0xc000374530, 0xc00010e960)
        /home/runner/work/ghz/ghz/load/worker_ticker.go:109 +0x6e
created by github.com/bojand/ghz/load.(*StepWorkerTicker).Run
        /home/runner/work/ghz/ghz/load/worker_ticker.go:79 +0x1b9

**To Reproduce**
Steps to reproduce the behavior: just run this command

**Expected behavior**
down without panic

**Environment**
 - OS: [Ubuntu 20.04]
 - ghz: [0.90.0]
 
**Screenshots**

**Additional context**
if adjust arguments `-n` to 10000,it works。

**Comment by lixd** [comment]
when I update to 0.94.0 it works. maybe it's fixed in those version？

**Comment by alpha-baby** [comment]
I also encountered this bug

**Comment by alpha-baby** [comment]
```bash
$ ghz --proto helloworld.proto --insecure --call helloworld.Greeter.SayHello -d '{"name": "jack"}' -z 1m --concurrency-schedule=step --concurrency-start=8000 --concurrency-step=200 --concurrency-step-duration=5s --concurrency-max-duration=120s 127.0.0.1:50051
panic: send on closed channel

goroutine 2667295 [running]:
github.com/bojand/ghz/runner.(*statsHandler).HandleRPC(0xc000464410, 0x1844e80, 0xc00cf5f9e0, 0x183e9c0, 0xc00f371a40)
	github.com/bojand/ghz/runner/stats_handler.go:52 +0x1ef
google.golang.org/grpc.(*csAttempt).finish(0xc013b01780, 0x1839220, 0xc0001b86f0)
	google.golang.org/grpc@v1.34.0/stream.go:1011 +0x457
google.golang.org/grpc.(*clientStream).newAttemptLocked.func1(0xc008f2d8e0, 0xc013b01780)
	google.golang.org/grpc@v1.34.0/stream.go:357 +0x50
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc0124c6fc0, 0x1844f98, 0xc000464410, 0x0, 0x1839220, 0xc0001b86f0)
	google.golang.org/grpc@v1.34.0/stream.go:375 +0x3de
google.golang.org/grpc.newClientStream(0x1844e80, 0xc00cf5f9e0, 0x1c136a0, 0xc0003f9180, 0xc00ede9a20, 0x1c, 0xc0003fe220, 0x2, 0x2, 0x0, ...)
	google.golang.org/grpc@v1.34.0/stream.go:297 +0x9d3
google.golang.org/grpc.invoke(0x1844e80, 0xc00cf5f8f0, 0xc00ede9a20, 0x1c, 0x1767d40, 0xc0003af890, 0x1767d40, 0xc00cf5f920, 0xc0003f9180, 0xc0003fe220, ...)
	google.golang.org/grpc@v1.34.0/call.go:66 +0x99
google.golang.org/grpc.(*ClientConn).Invoke(0xc0003f9180, 0x1844e80, 0xc00cf5f8f0, 0xc00ede9a20, 0x1c, 0x1767d40, 0xc0003af890, 0x1767d40, 0xc00cf5f920, 0x1c42d30, ...)
	google.golang.org/grpc@v1.34.0/call.go:37 +0x1b3
github.com/jhump/protoreflect/dynamic/grpcdynamic.Stub.InvokeRpc(0x183e740, 0xc0003f9180, 0x0, 0x1844e80, 0xc00cf5f8f0, 0xc0002c3bd0, 0x1843190, 0xc0003af890, 0x1c42d30, 0x0, ...)
	github.com/jhump/protoreflect@v1.5.0/dynamic/grpcdynamic/stub.go:61 +0x2ea
github.com/bojand/ghz/runner.(*Worker).makeUnaryRequest(0xc004e39650, 0xc008f2de70, 0xc0043548f8, 0xc0003af890, 0x0, 0x0)
	github.com/bojand/ghz/runner/worker.go:177 +0xb9
github.com/bojand/ghz/runner.(*Worker).makeRequest(0xc004e39650, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/bojand/ghz/runner/worker.go:163 +0x628
github.com/bojand/ghz/runner.(*Worker).runWorker(0xc004e39650, 0x179c268, 0xc00532e7c8)
	github.com/bojand/ghz/runner/worker.go:63 +0x205
github.com/bojand/ghz/runner.(*Requester).runWorkers.func2.1(0xc00048c0c0, 0xc004e39650)
	github.com/bojand/ghz/runner/requester.go:407 +0x2b
created by github.com/bojand/ghz/runner.(*Requester).runWorkers.func2
	github.com/bojand/ghz/runner/requester.go:406 +0x65
panic: send on closed channel

goroutine 2667303 [running]:
github.com/bojand/ghz/runner.(*statsHandler).HandleRPC(0xc000464410, 0x1844e80, 0xc00e3c2e10, 0x183e9c0, 0xc00f6888c0)
	github.com/bojand/ghz/runner/stats_handler.go:52 +0x1ef
google.golang.org/grpc.(*csAttempt).finish(0xc00ff9ca80, 0x1839220, 0xc0001b86f0)
	google.golang.org/grpc@v1.34.0/stream.go:1011 +0x457
google.golang.org/grpc.(*clientStream).newAttemptLocked.func1(0xc00a92d8e0, 0xc00ff9ca80)
	google.golang.org/grpc@v1.34.0/stream.go:357 +0x50
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc012692480, 0x1844f98, 0xc000464410, 0x0, 0x1839220, 0xc0001b86f0)
	google.golang.org/grpc@v1.34.0/stream.go:375 +0x3de
google.golang.org/grpc.newClientStream(0x1844e80, 0xc00e3c2e10, 0x1c136a0, 0xc0003f9180, 0xc00eb95aa0, 0x1c, 0xc0003fe220, 0x2, 0x2, 0x0, ...)
	google.golang.org/grpc@v1.34.0/stream.go:297 +0x9d3
google.golang.org/grpc.invoke(0x1844e80, 0xc00e3c2b70, 0xc00eb95aa0, 0x1c, 0x1767d40, 0xc0003af890, 0x1767d40, 0xc00e3c2ba0, 0xc0003f9180, 0xc0003fe220, ...)
	google.golang.org/grpc@v1.34.0/call.go:66 +0x99
google.golang.org/grpc.(*ClientConn).Invoke(0xc0003f9180, 0x1844e80, 0xc00e3c2b70, 0xc00eb95aa0, 0x1c, 0x1767d40, 0xc0003af890, 0x1767d40, 0xc00e3c2ba0, 0x1c42d30, ...)
	google.golang.org/grpc@v1.34.0/call.go:37 +0x1b3
github.com/jhump/protoreflect/dynamic/grpcdynamic.Stub.InvokeRpc(0x183e740, 0xc0003f9180, 0x0, 0x1844e80, 0xc00e3c2b70, 0xc0002c3bd0, 0x1843190, 0xc0003af890, 0x1c42d30, 0x0, ...)
	github.com/jhump/protoreflect@v1.5.0/dynamic/grpcdynamic/stub.go:61 +0x2ea
github.com/bojand/ghz/runner.(*Worker).makeUnaryRequest(0xc004e399d0, 0xc00a92de70, 0xc004ebd688, 0xc0003af890, 0x0, 0x0)
	github.com/bojand/ghz/runner/worker.go:177 +0xb9
github.com/bojand/ghz/runner.(*Worker).makeRequest(0xc004e399d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/bojand/ghz/runner/worker.go:163 +0x628
github.com/bojand/ghz/runner.(*Worker).runWorker(0xc004e399d0, 0x179c268, 0xc007dedfc8)
	github.com/bojand/ghz/runner/worker.go:63 +0x205
github.com/bojand/ghz/runner.(*Requester).runWorkers.func2.1(0xc00048c0c0, 0xc004e399d0)
	github.com/bojand/ghz/runner/requester.go:407 +0x2b
created by github.com/bojand/ghz/runner.(*Requester).runWorkers.func2
	github.com/bojand/ghz/runner/requester.go:406 +0x65
panic: send on closed channel

goroutine 2667346 [running]:
github.com/bojand/ghz/runner.(*statsHandler).HandleRPC(0xc000464410, 0x1844e80, 0xc00f974360, 0x183e9c0, 0xc00d90f9f0)
	github.com/bojand/ghz/runner/stats_handler.go:52 +0x1ef
google.golang.org/grpc.(*csAttempt).finish(0xc00c4e2d00, 0x1839220, 0xc0001b86f0)
	google.golang.org/grpc@v1.34.0/stream.go:1011 +0x457
google.golang.org/grpc.(*clientStream).newAttemptLocked.func1(0xc0050e78e0, 0xc00c4e2d00)
	google.golang.org/grpc@v1.34.0/stream.go:357 +0x50
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc00d68cea0, 0x1844f98, 0xc000464410, 0x0, 0x1839220, 0xc0001b86f0)
	google.golang.org/grpc@v1.34.0/stream.go:375 +0x3de
google.golang.org/grpc.newClientStream(0x1844e80, 0xc00f974360, 0x1c136a0, 0xc0003f9180, 0xc0129c7e20, 0x1c, 0xc0003fe220, 0x2, 0x2, 0x0, ...)
	google.golang.org/grpc@v1.34.0/stream.go:297 +0x9d3
google.golang.org/grpc.invoke(0x1844e80, 0xc00f974270, 0xc0129c7e20, 0x1c, 0x1767d40, 0xc0003af890, 0x1767d40, 0xc00f9742a0, 0xc0003f9180, 0xc0003fe220, ...)
	google.golang.org/grpc@v1.34.0/call.go:66 +0x99
google.golang.org/grpc.(*ClientConn).Invoke(0xc0003f9180, 0x1844e80, 0xc00f974270, 0xc0129c7e20, 0x1c, 0x1767d40, 0xc0003af890, 0x1767d40, 0xc00f9742a0, 0x1c42d30, ...)
	google.golang.org/grpc@v1.34.0/call.go:37 +0x1b3
github.com/jhump/protoreflect/dynamic/grpcdynamic.Stub.InvokeRpc(0x183e740, 0xc0003f9180, 0x0, 0x1844e80, 0xc00f974270, 0xc0002c3bd0, 0x1843190, 0xc0003af890, 0x1c42d30, 0x0, ...)
	github.com/jhump/protoreflect@v1.5.0/dynamic/grpcdynamic/stub.go:61 +0x2ea
github.com/bojand/ghz/runner.(*Worker).makeUnaryRequest(0xc00e7a97a0, 0xc0050e7e70, 0xc004e7cb90, 0xc0003af890, 0x0, 0x0)
	github.com/bojand/ghz/runner/worker.go:177 +0xb9
github.com/bojand/ghz/runner.(*Worker).makeRequest(0xc00e7a97a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/bojand/ghz/runner/worker.go:163 +0x628
github.com/bojand/ghz/runner.(*Worker).runWorker(0xc00e7a97a0, 0x179c268, 0xc004630fc8)
	github.com/bojand/ghz/runner/worker.go:63 +0x205
github.com/bojand/ghz/runner.(*Requester).runWorkers.func2.1(0xc00048c0c0, 0xc00e7a97a0)
	github.com/bojand/ghz/runner/requester.go:407 +0x2b
created by github.com/bojand/ghz/runner.(*Requester).runWorkers.func2
	github.com/bojand/ghz/runner/requester.go:406 +0x65
panic: send on closed channel

goroutine 2667240 [running]:
github.com/bojand/ghz/runner.(*statsHandler).HandleRPC(0xc000464410, 0x1844e80, 0xc010791470, 0x183e9c0, 0xc00dba3c20)
	github.com/bojand/ghz/runner/stats_handler.go:52 +0x1ef
google.golang.org/grpc.(*csAttempt).finish(0xc012c6de00, 0x1839220, 0xc0001b86f0)
	google.golang.org/grpc@v1.34.0/stream.go:1011 +0x457
google.golang.org/grpc.(*clientStream).newAttemptLocked.func1(0xc0054698e0, 0xc012c6de00)
	google.golang.org/grpc@v1.34.0/stream.go:357 +0x50
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc0124158c0, 0x1844f98, 0xc000464410, 0x0, 0x1839220, 0xc0001b86f0)
	google.golang.org/grpc@v1.34.0/stream.go:375 +0x3de
google.golang.org/grpc.newClientStream(0x1844e80, 0xc010791470, 0x1c136a0, 0xc0003f9180, 0xc011b84ea0, 0x1c, 0xc0003fe220, 0x2, 0x2, 0x0, ...)
	google.golang.org/grpc@v1.34.0/stream.go:297 +0x9d3
google.golang.org/grpc.invoke(0x1844e80, 0xc010791380, 0xc011b84ea0, 0x1c, 0x1767d40, 0xc0003af890, 0x1767d40, 0xc0107913b0, 0xc0003f9180, 0xc0003fe220, ...)
	google.golang.org/grpc@v1.34.0/call.go:66 +0x99
google.golang.org/grpc.(*ClientConn).Invoke(0xc0003f9180, 0x1844e80, 0xc010791380, 0xc011b84ea0, 0x1c, 0x1767d40, 0xc0003af890, 0x1767d40, 0xc0107913b0, 0x1c42d30, ...)
	google.golang.org/grpc@v1.34.0/call.go:37 +0x1b3
github.com/jhump/protoreflect/dynamic/grpcdynamic.Stub.InvokeRpc(0x183e740, 0xc0003f9180, 0x0, 0x1844e80, 0xc010791380, 0xc0002c3bd0, 0x1843190, 0xc0003af890, 0x1c42d30, 0x0, ...)
	github.com/jhump/protoreflect@v1.5.0/dynamic/grpcdynamic/stub.go:61 +0x2ea
github.com/bojand/ghz/runner.(*Worker).makeUnaryRequest(0xc009583e30, 0xc005469e70, 0xc004cf0160, 0xc0003af890, 0x0, 0x0)
	github.com/bojand/ghz/runner/worker.go:177 +0xb9
github.com/bojand/ghz/runner.(*Worker).makeRequest(0xc009583e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/bojand/ghz/runner/worker.go:163 +0x628
github.com/bojand/ghz/runner.(*Worker).runWorker(0xc009583e30, 0x179c268, 0xc004250fc8)
	github.com/bojand/ghz/runner/worker.go:63 +0x205
github.com/bojand/ghz/runner.(*Requester).runWorkers.func2.1(0xc00048c0c0, 0xc009583e30)
	github.com/bojand/ghz/runner/requester.go:407 +0x2b
created by github.com/bojand/ghz/runner.(*Requester).runWorkers.func2
	github.com/bojand/ghz/runner/requester.go:406 +0x65
```

**Comment by bojand** [comment]
Should be fixed in #286 and released in [0.96.0](https://github.com/bojand/ghz/releases/tag/v0.96.0).

**Comment by lramosduarte** [comment]
Apparently same issue here when i send this:
```bash
ghz --data="{}" --async --proto=proto.pb \
-n 1000 --rps 200 \
--concurrency 200 --connections 100 --concurrency-schedule=step --concurrency-start=5 
--concurrency-step=5 --concurrency-end=50 --concurrency-step-duration=5s \
--timeout=50s  \
--format=html --output=result.html --call=method:port
```
If a remove `--async` it's work, but so slow.
**Ps: My method are an bidirectional stream!**

**Comment by HC-miss** [comment]
> 

I got this error with version 0.108.0
